### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by nishafrh** [Chang-Chia-Chi/TrackNet-Badminton-Tracking-tensorflow2#13]
> (tf) PS D:\Users\TrackNet-Badminton-Tracking-tensorflow2-main> python train.py --tol=5.0 --save_weights=weights/TrackNet --HEIGHT=288 --WIDTH=512 --batch_size=2 --frame_stack=3 --pre_trained=False

2023-03-02 11:05:04.983939: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-02 11:05:05.386475: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3989 MB memory:  -> device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5
Beginning training......
==========Epoch 0, Train steps: 261, Learning rate: 1.0000==========
2023-03-02 11:05:06.519304: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8201
2023-03-02 11:05:22.070226: W tensorflow/core/common_runtime/bfc_allocator.cc:290] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.55GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.
2023-03-02 11:05:22.070382: W tensorflow/core/common_runtime/bfc_allocator.cc:290] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.55GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.
261/261 [==============================] - 87s 284ms/step - loss: 2.8470e-05 - binary_accuracy: 0.9998
==========Epoch 0 start validation==========
1/1 [==============================] - 1s 1s/step
Traceback (most recent call last):
  File "D:\Users\TrackNet-Badminton-Tracking-tensorflow2-main\train.py", line 69, in <module>
    tp, tn, fp1, fp2, fn = confusion(y_pred, y_batch[:, 0,...], tol)
  File "D:\Users\TrackNet-Badminton-Tracking-tensorflow2-main\utils.py", line 189, in confusion
    _, contours, _ = cv2.findContours(h_pred[0].copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by YannickGibson** [comment]
try opencv-python<4.0
